apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2016-08-12T09:07:56Z
  generation: 3
  labels:
    run: go-web-server
  name: go-web-server
  namespace: default
  resourceVersion: "44571"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/go-web-server
  uid: 427af6ca-606c-11e6-8007-aab5d29d70f1
spec:
  replicas: 4
  selector:
    matchLabels:
      run: go-web-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: go-web-server
    spec:
      containers:
      - image: docker.io/mingder78/devops-go-web-server
        imagePullPolicy: Always
        name: go-web-server
        ports:
        - containerPort: 1323
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  observedGeneration: 3
  replicas: 4
  updatedReplicas: 4
